[package]
name = "rustdesk_auto_config"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
runas = "1.2.0"
toml_edit = "0.22.27"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
